apiVersion: v1
kind: PersistentVolume
metadata:
  name: free5gc-mongodb-pv
spec:
  capacity:
    storage: 8Gi
  accessModes: [ReadWriteOnce]
  storageClassName: microk8s-hostpath
  local:
    path: /var/snap/microk8s/common/default-storage/mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [YOUR_NODE_NAME_HERE]